version: "3"
services:
  influxdb:
    image: influxdb:2.6.0-alpine
    volumes:
      - ./myInfluxDBVolume:/var/lib/influxdb2
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
    networks:
      - external
  grafana:
    image: grafana/grafana-oss:9.3.2
    ports:
      - 8080:3000
    user: "0:0"
    depends_on:
      - influxdb
    environment:
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    networks:
      - external

networks:
  external:
    external: true
